syntax = "proto3";

package ntx.core20;
option csharp_namespace = "ntx20.api.proto";

message Blob {
 // hex(sha1(body))
 string sha1 = 1;
 // relative path to app root
 // defaults to ${app_root}/${sha1} when archive not set, ${app_root} when archive is set
 string path = 2;
 // optional, supported values are [tgz, zip, tar]
 string archive = 3;
 // optional, [windows-x64, linux-x64]
 string platform = 4;

 repeated string tags = 5;
  
 int64 size = 6;
}


message App {
  // ntx20
  string name = 1;
  // 1.2.4
  string version = 2;
  repeated Blob blobs = 3;

  // 210225-150412
  string createdTime = 4;

  map<string, string> labels = 5;
}

message Service{
	repeated ServiceVersion versions = 1;
}
message ServiceVersion {
  // name must be group + '.' + version
  //ServiceMeta meta = 1;
  string service = 1;
  string version = 2;
  map<string, string> labels = 3;
  // e.g. cz-broadcast, may not contain '.'
  repeated string cmd = 4;
  map<string, string> env = 5;

  repeated Blob blobs = 6;

  int64 expireTime = 7;
}
